example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('', show_mywatchlist, name='show_mywatchlist'),
    
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist, show_todolist_json, register, login_user, create_task, toggle, delete, logout_user

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name ='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('create_task/', create_task, name='create_task'),
    path('toggle-task/<int:pk>', toggle, name='toggle'),
    path('delete-task/<int:pk>', delete, name='delete'),
    path('logout/', logout_user, name='logout'),
    path('json/', show_todolist_json, name='show_todolist_json'),

]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchList(models.Model):
    watched = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)
    status = models.CharField(max_length=13, default='Belum Selesai')

    def __str__(self):
        return self.title

todolist/forms.py
from django.forms import ModelForm
from todolist.models import Task

class CreateNewTask(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem
# TODO: Create your views here.
def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_barang_katalog,
        'nama': 'Ihza Dafa Maulidan',
        'npm': '2106652726'
}
    return render(request, "katalog.html", context)
    

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    datamywatchlist = MyWatchList.objects.all()
    count = 0
    for film in datamywatchlist:
        if film.is_watched == "Yes":
            count += 1
    if count >= 5:
        isi = "Selamat, kamu sudah banyak menonton!"
    else:
        isi = "Wah, kamu masih sedikit menonton!"

    context = {
        'mywatchlist': datamywatchlist,
        'nama': 'Ihza Dafa Maulidan',
        'npm': '2106652726',
        'pesan': isi
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
import datetime
from dataclasses import dataclass
from todolist.models import Task
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from todolist.forms import CreateNewTask
from django.core import serializers


# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = Task.objects.filter(user = request.user)
    context = {
    'list_todolist': data_todolist,
    'nama': 'Ihza Dafa Maulidan',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_todolist_json(request):
    data_todolist = Task.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data_todolist), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def create_task(request): ####    
    form = CreateNewTask(request.POST)

    if request.method == 'POST':
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            return response

    context = {'form': form}
    return render(request, 'create_task.html', context)

def delete(request, pk):
    data = Task.objects.get(id=pk)
    data.delete()
    response = HttpResponseRedirect(reverse("todolist:show_todolist"))
    return response

def toggle(request, pk):
    data = Task.objects.get(id=pk)
    if data.is_finished == True:
        data.is_finished = False
    else:
        data.is_finished = True
    data.save()
    response = HttpResponseRedirect(reverse("todolist:show_todolist"))
    return response

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>TUGAS 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <h3>{{pesan}}</h3>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in mywatchlist %}
    <tr>
        <th>{{film.is_watched}}</th>
        <th>{{film.title}}</th>
        <th>{{film.rating}}</th>
        <th>{{film.release_date}}</th>
        <th>{{film.review}}</th>
    </tr>
  {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html> 

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}  
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js%22%3E"></script>
<style>
    body {
      background-image: url(https://docs.google.com/uc?id=1M3IAYW6UYk0ycoTfyI84u7vPI2BgZCPA);
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    } 

    * {
        font-family:'Times New Roman', Times, serif;
        text-align: center;
        vertical-align: middle;
    }

    h1 {
        margin-top: 50px;
        color: red;
        font-weight: bolder;
    }

    table, th, td {
        margin-left: auto;
        margin-right: auto;
        border-collapse: collapse;
        width: 250px;
        padding: 10px 14px
    }

    table {
        border-radius: 10px;
        background-color:rgba(56, 67, 208, 0.2);
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }

    table:hover {
        background-color:rgba(56, 67, 208, 0.2);
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.75);
    }

    input.btn {
      background-color: red;
      color: white;
      border: 1px solid black;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.1);
    }

    input.btn:hover {
      background-color: red;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.5);
      color: white;
      border: 1px solid black;
    }

    input.btn:active {
      background-color: red;
      color: white;
      border: 1px solid black;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.1);
    }

    
    ul, li {
        text-align: center;
        list-style: none;
    }

</style>

<h1>Create Task</h1>  

    <form style="color: white"method="POST" >  
        {% csrf_token %}  
        <table>  
            <tr>
                <td></td>
                <td>{{form}}</td>
            </tr>
            <tr>  
                <td></td>
                <td><input class = "btn" type="submit" name="submit" value="Post"/></td>  
            </tr>  
        </table>  
    </form>


{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js%22%3E"></script>

<style>
    body {
      background-image: url(https://docs.google.com/uc?id=1M3IAYW6UYk0ycoTfyI84u7vPI2BgZCPA);
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
      align-items: center;
      background-color: #000;
      display: flex;
      justify-content: center;
    } 

    * {
        font-family:'Times New Roman', Times, serif;
        text-align: center;
        vertical-align: middle;
    }

    h1 {
        margin-top: 190px;
        color: #FF1E1E;
        font-weight: bolder;
    }
    table, th, td {
        margin-left: auto;
        margin-right: auto;
        border-collapse: collapse;
        width: 250px;
        padding: 10px 14px
    }

    table {
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        background-color:rgba(56, 67, 208, 0.2);
        margin-bottom: 10px;
    }

    table:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.75);
    }

    input.btn {
      background-color: red;
      color: white;
      border: 1px solid black;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.1);
    }

    input.btn:hover {
      background-color: red;
      color: white;
      border: 1px solid black;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.5);
    }

    input.btn:active {
      background-color: red;
      color: white;
      border: 1px solid black;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.1);
    }

    a.Redirect:hover {
      box-shadow: 0 1px 1px 0 rgba(0,0,0,0.5);
    }

</style>

<body>
  <div class = "login">
    <h1>Login</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td class = "button" ><input class="btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}   
        
    <p style="color: white">Don't have an account? <a style="color: rgb(220, 82, 13)" class= "Redirect" href="{% url 'todolist:register' %}">Create Here</a></p>

</div>
</body>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js%22%3E"></script>
<style>
    body {
      background-image: url(https://docs.google.com/uc?id=1M3IAYW6UYk0ycoTfyI84u7vPI2BgZCPA);
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
      align-items: center;
      background-color: #000;
      display: flex;
      justify-content: center;
    } 

    * {
        font-family:'Times New Roman', Times, serif;
        text-align: center;
        vertical-align: middle;
    }

    h1 {
        margin-top: 75px;
        color: red;
        font-weight: bolder;
    }
    
    table, th, td{
        margin-left: auto;
        margin-right: auto;
        border-collapse: collapse;
    }
    
    table {
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        background-color:rgba(56, 67, 208, 0.2);
        width: 1000px;
        height: 400px;
    }

    table:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.75);
    }

    input.btn {
      background-color: red;
      color: white;
      border: 1px solid black;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.1);
    }

    input.btn:hover {
      background-color: red;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.5);
      color: white;
      border: 1px solid black;
    }

    input.btn:active {
      background-color: red;
      color: white;
      border: 1px solid black;
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.1);
    }

    ul, li {
        text-align: center;
        list-style: none;
    }


</style>

<div class = "login" style="color: white"> 
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input class="btn" type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>


</div> 

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
    $(document).ready(() => {
        getTaskList();
    })

    function createTask() {
        const form = $(".create_task");
        $.ajax({
            type: "POST",
            url: "/todolist/create_task/",
            data: form.serialize(),
        }).done(function (data) {
            form.trigger("reset");
            getTaskList();
        });
        $("#staticBackdrop").modal("hide");
    }

    function deleteTask(id) {
        $.ajax({
            type: "GET",
            url: "/todolist/delete-task/" + id,
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
        }).done((data) => {
            getTaskList();
        })
    }

    function toggleTaskStatus(id) {
        $.ajax({
            type: "GET",
            url: "/todolist/toggle-task/" + id,
            data: {csrfmiddlewaretoken: '{{ csrf_token }}', pk: id}
        }).done((data) => {
            getTaskList();
        })
    }

    function getTaskList() {
        $.ajax({
            type: "GET",
            url: "/todolist/json/"
        }).done((data) => {
            putTaskList(data);
        });
    }

    function putTaskList(data) {
        console.log("LOOK HERE" + data)
        const cardContainer = $('.cardContainer');
        cardContainer.empty();
        data.forEach(task => {
            const taskCard = `
            <div class="card" style="width: 350px;">
              <div class="card-body">
                <h5 class="card-title">${task.fields.title}</h5>
                <h6 class="card-subtitle mb-2 text-muted">${task.fields.date}</h6>
                <p class="card-text">${task.fields.description}</p>
                ${task.fields.is_finished ? "Selesai" : "Belum Selesai"} <br>
                
                <td class="change-status-btn" style="padding:10px;">
                    <input type="submit" value="Change Status" class="btn btn-primary toggleButton" onclick="toggleTaskStatus(${task.pk})" />
                </td>
                <td class="delete-task-btn" style="padding:10px;">
                    <input type="submit" value="Delete Task"  class="btn btn-danger toggleButton" onclick="deleteTask(${ task.pk })" />
                </td>
              </div>
            </div>
            `
            cardContainer.append(taskCard);
        })
    };
</script>

  <style>
  body {
    background-image: url(https://docs.google.com/uc?id=1M3IAYW6UYk0ycoTfyI84u7vPI2BgZCPA);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }

  * {
    font-family:'Times New Roman', Times, serif;
    text-align: left;
    vertical-align: middle; 
  }

  h2 {
    padding-top: 20px;
    text-align: center;
    font-weight: bolder;
    color: red;
  }

  h5.text-muted {
    text-align: left;
    margin-left: 160px;
    text-align: left;
    color: red;;
    font-family:'Times New Roman', Times, serif
  }

  h6 {
    margin-top: 10px;
    
  }

  .card {
    margin-top: 10px;
    margin-bottom: auto;
    margin-left: auto;
    margin-right: auto;
    border: 1px solid red;
    border-radius: 10px;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    background-color:rgba(56, 67, 208, 0.2);
    color:white
  }

  .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.75);
  }
  
  .button {
        border-width: 1px;
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        background-color:red;
        border: 1px solid red;
        color: white;
        padding: 4px 8px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin: 4px 2px;
        cursor: pointer;
  }

  .CreateTaskButton {
    font-family:'Times New Roman', Times, serif;
    border: 1px solid red;
    background-color:red;
    color: white;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
  }

  .CreateTaskButton:hover {
    font-family:'Times New Roman', Times, serif;
    border: 1px solid red;
    background-color:red;
    color: white;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.75);
  }

  .CreateTaskButton:activate {
    font-family:'Times New Roman', Times, serif;
    border: 1px solid red;
    background-color:red;
    color: white;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
  }

  .toggleButton {
    font-family:'Times New Roman', Times, serif;
    border: 1px solid red;
    background-color:red;
    color: white;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
  }

  .toggleButton:hover {
    font-family:'Times New Roman', Times, serif;
    border: 1px solid red;
    background-color:red;
    color: white;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.75);
  }

  .toggleButton:activate {
    font-family:'Times New Roman', Times, serif;
    border: 1px solid red;
    background-color:red;
    color: white;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
  }


  .button:hover {
    border: 1px solid red;
    color: white;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.75);
  }

  .button:activate {
    border: 1px solid red;
    color: white;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.1);
  }

  </style>

  <h2>My Todolist<h2>

  <h5 class="text-muted">User logged in: {{user}} </h5>

  <div class="cardContainer">
    
  </div>
  
  <h6 class="text-muted">Sesi terakhir login: {{ last_login }}</h6>
<button type="button" class="btn btn-primary CreateTaskButton" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Create a new task</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Task Details</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form class="create_task" method="POST">
              {% csrf_token %}
              <div class="form-floating responsive" style="padding-left:0.5%;margin-top: 2%;">
                <input 
                type="text" 
                class="form-control" 
                id="floatingInput" 
                name="title" 
                placeholder="Title">
                <label for="floatingInput">Title</label>
              </div>
            
              <div class="form-floating responsive" style="padding-left:0.5%;margin-top: 2%;">
                <textarea 
                class="form-control" 
                id="floatingDescription" 
                name="description" rows="4" cols="50" placeholder="Description"></textarea>
                <label for="floatingDescription" style="padding-left:2.5%;">Description</label>
              </div>
            </form>
      </div>
      <div class="modal-footer">
        <button type="button" style="background-color: red; color: white;" data-bs-dismiss="modal">Close</button>
        <button type="button" style="background-color: red; color: white;" onclick="createTask()">Create Task</button>
      </div>
    </div>
  </div>
</div>  

<a href="{% url 'todolist:logout' %}" style="text-decoration: none;" class = "button">Logout</a>

 {% endblock content %}